included:
    - "Sources"
    - "SampleApplication"

excluded:
     
opt_in_rules:
    - accessibility_label_for_image
    - accessibility_trait_for_button
    - array_init
    - block_based_kvo
    - class_delegate_protocol
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon # promote to error
    - comma
    - compiler_protocol_init
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - control_statement
    - custom_todo
    - direct_return
    - discouraged_direct_init
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discarded_notification_center_observer
    - duplicate_enum_cases
    - duplicate_imports
    - dynamic_inline
    - empty_collection_literal
    - empty_count
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - explicit_init
    - fallthrough
    - fatal_error_message
    - file_header
    - first_where
    - flatmap_over_map_reduce
    - for_where
    - force_cast
    - force_try
    - force_unwrapping
    - identical_operands
    - implicit_getter
    - implicitly_unwrapped_optional
    - is_disjoint
    - joined_default_parameter
    - last_where
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_multiple
    - legacy_nsgeometry_functions
    - legacy_random
    - literal_expression_end_indentation
    - local_doc_comment
    - lower_acl_than_parent
    - mark
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - multiple_closures_with_trailing_closure
    - nslocalizedstring_key
    - no_space_in_method_call
    - non_overridable_class_declaration
    - notification_center_detachment
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - period_spacing
    - prefer_self_in_static_references
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_action
    - private_outlet
    - private_over_fileprivate
    - private_subject
    - private_swiftui_state
    - private_unit_test
    - prohibited_super_call
    - protocol_property_accessors_order
    - redundant_discardable_let
    - redundant_nil_coalescing
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_type_annotation
    - redundant_void_return
    - reduce_boolean
    - required_enum_case
    - return_arrow_whitespace
    - return_value_from_void_function
    - shorthand_operator
    - single_test_class
    - sorted_first_last
    - statement_position
    - strict_fileprivate
    - superfluous_disable_command
    - switch_case_alignment
    - syntactic_sugar
    - test_case_accessibility
    - toggle_bool
    - trailing_closure
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - unavailable_function
    - unneeded_break_in_switch
    - unneeded_override
    - unneeded_parentheses_in_closure_argument
    - unneeded_synthesized_initializer
    - unused_closure_parameter
    - unused_control_flow_label
    - unused_enumerated
    - unused_import
    - unused_optional_binding
    - unused_setter_value
    - valid_ibinspectable
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - vertical_whitespace_closing_braces
    - void_return
    - weak_delegate
    - xctfail_message
    - yoda_condition

disabled_rules:
    - trailing_whitespace

#    - blanket_disable_command
#    - discarded_notification_center_observer
#    - notification_center_detachment
#    - orphaned_doc_comment
#    - unused_capture_list
#    - switch_case_alignment
#    - multiline_arguments
#    - multiline_parameters_brackets
#    - multiline_literal_brackets
#    - class_delegate_protocol
#    - nesting

line_length:
     warning: 160
     error: 210
     ignores_urls: true

identifier_name:
  allowed_symbols:
    - "_"
  excluded:
    - id

file_header:
  required_pattern: |
    \/\/  Copyright (©|\(c\)) \d{4} .*?\. All rights reserved\.
